RegistryWeb/Controllers/OwnerProcessesController.cs
using System;
using System.IO;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RegistryWeb.DataServices;
using RegistryWeb.SecurityServices;
using RegistryWeb.ViewOptions.Filter;
using RegistryWeb.Enums;
using RegistryServices.ViewModel.Owners;
using RegistryDb.Models.Entities.Owners;
using RegistryWeb.Filters;

namespace RegistryWeb.Controllers
{
    [Authorize]
    [HasPrivileges(Privileges.OwnerRead)]
    [DefaultResponseOnException(typeof(Exception))]
    public class OwnerProcessesController : ListController<OwnerProcessesDataService, OwnerProcessesFilter>
    {        
        public OwnerProcessesController(OwnerProcessesDataService dataService, SecurityService securityService)
            : base(dataService, securityService)
        {
        }

        public IActionResult Index(OwnerProcessesVM viewModel)
        {
            if (viewModel.PageOptions != null && viewModel.PageOptions.CurrentPage < 1)
                return NotFound();
            ViewBag.SecurityService = securityService;
            return View(dataService.GetViewModel(
                viewModel.OrderOptions,
                viewModel.PageOptions,
                viewModel.FilterOptions));
        }

        [HttpGet]
        [HasPrivileges(Privileges.OwnerWrite)]
        public IActionResult Create(OwnerProcessesFilter filterOptions, string returnUrl)
        {
            return GetOwnerProcessView(dataService.CreateOwnerProcess(filterOptions), returnUrl);
        }

        [HttpPost]
        [HasPrivileges(Privileges.OwnerWrite)]
        public IActionResult Create(OwnerProcess ownerProcess, string returnUrl, IFormFileCollection attachmentFiles)
        {
            if (ownerProcess == null)
                return NotFound();
            if (ModelState.IsValid)
            {
                dataService.Create(ownerProcess, attachmentFiles);
                return RedirectToAction("Details", new { ownerProcess.IdProcess, returnUrl });
            }
            return Redirect(returnUrl);
        }

        [HttpPost]
        public IActionResult AddressAdd(int idProcess, int id, int i, string text, AddressTypes addressType, ActionTypeEnum action)
        {
            var addressVM = new OwnerProcessAddressVM();
            addressVM.AddressType = addressType;
            addressVM.Action = action;
            addressVM.IdProcess = idProcess;
            addressVM.IdAssoc = 0;
            addressVM.Id = id;
            addressVM.I = i;
            addressVM.Text = text;
            addressVM.Href = dataService.GetHrefToReestr(id, addressType);
            return PartialView("OwnerProcessAddress", addressVM);
        }

        [HttpPost]
        public IActionResult OwnerAdd(int idOwnerType, int i, ActionTypeEnum action)
        {
            var ownerVM = new OwnerVM();
            ownerVM.Owner = new Owner() { IdOwnerType = idOwnerType };
            ownerVM.Owner.IdOwnerTypeNavigation = dataService.GetOwnerType(idOwnerType);
            if (idOwnerType == 1)
                ownerVM.Owner.OwnerPerson = new OwnerPerson();
            if (idOwnerType == 2 || idOwnerType == 3)
                ownerVM.Owner.OwnerOrginfo = new OwnerOrginfo();
            ownerVM.I = i;
            ownerVM.Action = action;
            return PartialView("Owner", ownerVM);
        }

        [HttpPost]
        public IActionResult OwnerReasonAdd(int i, int j, ActionTypeEnum action)
        {
            var ownerReasonVM = new OwnerReasonVM();
            ownerReasonVM.OwnerReason = new OwnerReason();
            ownerReasonVM.OwnerReason.NumeratorShare = 1;
            ownerReasonVM.OwnerReason.DenominatorShare = 1;
            ownerReasonVM.OwnerReason.IdReasonType = 9; //Государственная регистрация права (ЕГРП)
            ownerReasonVM.OwnerReason.ReasonDate = DateTime.Now;
            ownerReasonVM.I = i;
            ownerReasonVM.J = j;
            ownerReasonVM.Action = action;
            ViewBag.OwnerReasonTypes = dataService.OwnerReasonTypes();
            return PartialView("OwnerReason", ownerReasonVM);
        }

        public IActionResult OwnerFileAdd(int i, ActionTypeEnum action)
        {
            var ownerFileVM = new OwnerFileVM()
            {
                OwnerFile = new OwnerFile() { DateDownload = DateTime.Now },
                Action = action,
                I = i
            };
            return PartialView("OwnerFile", ownerFileVM);
        }

        [HttpPost]
        public JsonResult AddressInfoGet(int id, AddressTypes addressType)
        {
            var addressInfo = dataService.GetAddressInfo(id, addressType);
            return Json(addressInfo);
        }

        [HttpPost]
        public IActionResult ProcessLogGet(int idProcess)
        {
            var processLog = dataService.GetProcessLog(idProcess);
            return PartialView("OwnerProcessLog", processLog);
        }

        [HttpGet]
        public IActionResult Details(int? idProcess, string returnUrl)
        {
            if (idProcess == null)
                return NotFound();
            var ownerProcess = dataService.GetOwnerProcess(idProcess.Value);
            if (ownerProcess == null)
                return NotFound();
            return GetOwnerProcessView(ownerProcess, returnUrl);
        }

        [HttpGet]
        [HasPrivileges(Privileges.OwnerWrite)]
        public IActionResult Delete(int? idProcess, string returnUrl)
        {
            if (idProcess == null)
                return NotFound();
            var ownerProcess = dataService.GetOwnerProcess(idProcess.Value);
            if (ownerProcess == null)
                return NotFound();
            return GetOwnerProcessView(ownerProcess, returnUrl);
        }

        [HttpPost]
        [HasPrivileges(Privileges.OwnerWrite)]
        public IActionResult Delete(OwnerProcess ownerProcess, string returnUrl)
        {
            if (ownerProcess == null)
                return NotFound();
            dataService.Delete(ownerProcess.IdProcess);
            return Redirect(returnUrl);            
        }

        [HttpGet]
        [HasPrivileges(Privileges.OwnerWrite)]
        public IActionResult Edit(int? idProcess, string returnUrl)
        {
            if (idProcess == null)
                return NotFound();
            var ownerProcess = dataService.GetOwnerProcess(idProcess.Value);
            if (ownerProcess == null)
                return NotFound();
            return GetOwnerProcessView(ownerProcess, returnUrl);
        }

        [HttpPost]
        [HasPrivileges(Privileges.OwnerWrite)]
        public IActionResult Edit(OwnerProcess ownerProcess, string returnUrl, IFormFileCollection attachmentFiles, bool[] removeFiles)
        {
            var r = Request;
            if (ownerProcess == null)
                return NotFound();
            if (ModelState.IsValid)
            {                
                dataService.Edit(ownerProcess, attachmentFiles, removeFiles);
                return RedirectToAction("Edit", new { ownerProcess.IdProcess, returnUrl });
            }
            return Redirect(returnUrl);
        }

        private IActionResult GetOwnerProcessView(OwnerProcess ownerProcess, string returnUrl, [CallerMemberName]string action = "")
        {
            var actionType = (ActionTypeEnum)Enum.Parse(typeof(ActionTypeEnum), action);
            ViewBag.Action = actionType;
            ViewBag.OwnerReasonTypes = dataService.OwnerReasonTypes();
            ViewBag.ReturnUrl = returnUrl;        
            return View("OwnerProcess", ownerProcess);
        }

        public IActionResult DownloadFile(int id)
        {
            var ownerFile = dataService.GetOwnerFile(id);           
            if (ownerFile == null) return Json(new { Error = -1 });
            var filePath = Path.Combine(dataService.AttachmentsPath, ownerFile.FileOriginName);
            if (!System.IO.File.Exists(filePath))
            {
                return Json(new { Error = -2 });
            }
            return File(System.IO.File.ReadAllBytes(filePath), ownerFile.FileMimeType, ownerFile.FileDisplayName);
        }
    }
}

RegistryWeb/Views/OwnerProcesses/DataTable.cshtml
@using RegistryWeb.Extensions;
@using RegistryWeb.ViewOptions;
@using RegistryWeb.SecurityServices;
@model RegistryServices.ViewModel.Owners.OwnerProcessesVM;
@{
    var securityService = (SecurityService)ViewData["SecurityService"];
    var canEdit = securityService.HasPrivilege(Privileges.OwnerWrite);
    var returnUrl = $"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}";
}
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                № по реестру
                @if (Model.OrderOptions.OrderDirection == OrderDirection.Ascending)
                {
                    <a href="#" class="oi oi-sort-descending sort " data-order-field="IdProcess" data-order-direction="1"></a>
                }
                else
                {
                    <a href="#" class="oi oi-sort-ascending sort" data-order-field="IdProcess" data-order-direction="0"></a>
                }
            </th>
            <th>Адрес</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OwnerProcesses)
        {
            var annulStyle = "";
            @if (item.AnnulDate != null)
            {
                annulStyle = "style=\"background-color:lightpink;\" title=\"Аннулирован\"";
            }
            <tr @Html.Raw(annulStyle)>
                <td class="align-middle" style="font-weight: bold">@item.IdProcess</td>
                <td class="align-middle">
                    @foreach (var addr in Model.Addresses[item.IdProcess])
                    {
                        @await Component.InvokeAsync("OwnerProcessesAddressComponent", new { address = addr, idProcess = item.IdProcess })
                    }
                </td>
                <td class="align-middle">
                    <div class="btn-group" role="group" aria-label="Панель доступа">
                        <button class="btn btn-primary oi oi-wrench dropdown-toggle" type="button" title="Инструменты" aria-label="Инструменты" id="toolsBtn_@item.IdProcess" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                        <div class="dropdown-menu dropdown-menu-right but text-center" aria-labelledby="toolsBtn_@item.IdProcess">
                            <a class="btn btn-primary oi oi-eye" title="Подробнее" aria-label="Подробнее"
                               asp-action="Details" asp-controller="OwnerProcesses" asp-route-idProcess="@item.IdProcess" asp-route-returnUrl="@returnUrl"></a>
                            <a class="btn btn-outline-dark oi oi-pencil @(canEdit ? "" : "disabled")" title="Изменить" aria-label="Изменить"
                               asp-action="Edit" asp-controller="OwnerProcesses" asp-route-idProcess="@item.IdProcess" asp-route-returnUrl="@returnUrl"></a>
                            <a class="btn btn-danger oi oi-x @(canEdit ? "" : "disabled")" title="Удалить" aria-label="Удалить"
                               asp-action="Delete" asp-controller="OwnerProcesses" asp-route-idProcess="@item.IdProcess" asp-route-returnUrl="@returnUrl"></a>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

RegistryWeb/Views/OwnerProcesses/Filter.cshtml
@model RegistryServices.ViewModel.Owners.OwnerProcessesVM;
@{ 
    var kladrStreetsList = new SelectList(Model.KladrStreets, "IdStreet", "StreetName", Model.FilterOptions.IdStreet);
    var ownerTypesList = new SelectList(Model.OwnerTypes, "IdOwnerType", "OwnerType1", Model.FilterOptions.IdOwnerType);
    var returnUrl = $"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}";
}
<form asp-action="Index" method="get" class="filterForm">
    <input type="hidden" name="OrderOptions.OrderDirection" value="@Model.OrderOptions.OrderDirection" />
    <input type="hidden" name="OrderOptions.OrderField" value="@Model.OrderOptions.OrderField" />
    <input type="hidden" name="PageOptions.CurrentPage" value="@Model.PageOptions.CurrentPage" />
    <input type="hidden" name="PageOptions.CurrentPage" value="@Model.PageOptions.CurrentPage" />
    <input type="hidden" name="FilterOptions.Address.AddressType" value="@Model.FilterOptions.Address.AddressType" />
    <input type="hidden" name="FilterOptions.Address.Id" value="@Model.FilterOptions.Address.Id" />
    <input type="hidden" name="returnUrl" value="@returnUrl" />
    <div class="form-row">
        <div class="form-group col-2 col-md-1 col-lg-1">
            <a href="#" id="createOwnerProcessBtn"class="btn btn-success" title="Создать" aria-label="Создать">&#10010;</a>
        </div>
        @if (Model.FilterOptions.IsAddressEmpty())
        {
            <div class="form-group col-7 col-md-9 col-lg-9">
                <input type="text" class="form-control rr-alt-address-search" title="Адрес" placeholder="Адрес"
                       name="FilterOptions.Address.Text" value="@Model.FilterOptions.Address.Text" />
            </div>
        }
        else
        {
            <div class="form-group col-7 col-md-9 col-lg-9">
                <div class="input-group">
                    <input type="text" class="form-control col rr-alt-address-search" title="Адрес" placeholder="Адрес"
                           name="FilterOptions.Address.Text" value="@Model.FilterOptions.Address.Text" />
                    <div class="input-group-append h-auto d-inline-block">
                        <button class="btn btn-outline-secondary" type="button" id="addressFilterClearBtn">&#10006;</button>
                    </div>
                </div>
            </div>
        }
        @if (Model.FilterOptions.IsModalEmpty())
        {
            <div class="form-group col-3 col-md-2 col-lg-2">
                <a class="btn btn-block btn-secondary" href="#" id="filterModalShow">Фильтр</a>
            </div>
        }
        else
        {
            <div class="form-group btn-group col-3 col-md-2 col-lg-2">
                <a class="btn btn-block btn-secondary" href="#" id="filterModalShow">Фильтр</a>
                <a class="btn btn-outline-secondary" href="#" id="filterClearBtn">&#10006;</a>
            </div>
        }
    </div>

    <!-- Modal -->
    <div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="ownerModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ownerModalLabel">Фильтр процессов собственности</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-lg-6 col-md-12">
                            <label asp-for="FilterOptions.IdStreet">Улица</label>
                            <select class="selectpicker form-control" data-live-search="true" title="Улица" asp-for="FilterOptions.IdStreet" asp-items="@kladrStreetsList"></select>
                        </div>
                        <div class="form-group col-lg-3 col-md-6">
                            <label asp-for="FilterOptions.House">Номер дома</label>
                            <input type="text" class="form-control input-filter-house" asp-for="FilterOptions.House" title="Номер дома">
                        </div>
                        <div class="form-group col-lg-3 col-md-6">
                            <label asp-for="FilterOptions.PremisesNum">Номер помещения</label>
                            <input type="text" class="form-control input-filter-premise-num" asp-for="FilterOptions.PremisesNum" title="Номер помещения">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-4">
                            <label asp-for="FilterOptions.IdProcess">Реестровый номер</label>
                            <input type="text" class="form-control input-filter-numbers" title="№ по реестру" placeholder="№ по реестру" asp-for="FilterOptions.IdProcess" />
                        </div>
                        <div class="form-group col-4">
                            <label asp-for="FilterOptions.IdProcessType">Тип процесса</label>
                            <select class="selectpicker form-control" asp-for="FilterOptions.IdProcessType" title="Тип процесса">
                                <option value="1">Действующие</option>
                                <option value="2">Аннулированные</option>
                            </select>
                        </div>
                        <div class="form-group col-4">
                            <label asp-for="FilterOptions.IdOwnerType">Тип собственников</label>
                            <select class="selectpicker form-control" asp-for="FilterOptions.IdOwnerType" title="Тип собственников"
                                    asp-items="@ownerTypesList"></select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="filterClearModalBtn" type="button" class="btn btn-secondary">Очистить</button>
                    <button id="searchModalBtn" type="button" class="btn btn-secondary" data-dismiss="modal">Найти</button>
                </div>
            </div>
        </div>
    </div>
</form>

RegistryWeb/Views/OwnerProcesses/Index.cshtml
@model RegistryServices.ViewModel.Owners.OwnerProcessesVM;
@{
    ViewData["Title"] = "Процессы собственности";
    var text = Model.PageOptions.TotalRows == Model.PageOptions.Rows ?
        "(" + Model.PageOptions.TotalRows + ")" :
        "(" + Model.PageOptions.Rows + " из " + Model.PageOptions.TotalRows + ")";
}

<h2>@ViewData["Title"] @text</h2>

<partial name="Filter" model="Model" />
<partial name="DataTable" model="Model" />
<page-link page-model="Model.PageOptions" page-action="Index"></page-link>

@section Scripts {
    <script src="~/js/address.filter.js" asp-append-version="true"></script>
    <script src="~/js/index.common.js" asp-append-version="true"></script>
    <script src="~/js/index.OwnerProcesses.js" asp-append-version="true"></script>
}

RegistryWeb/Views/OwnerProcesses/Owner.cshtml
@using RegistryServices.ViewModel.Owners;
@using RegistryWeb.Enums;
@model OwnerVM;
@{
    var i = Model.I;
    var canEdit = Model.Action == ActionTypeEnum.Edit || Model.Action == ActionTypeEnum.Create;
}
<li class="list-group-item rr-owner" data-i="@i">
    <input type="hidden" value="@Model.Owner.IdOwner" name="Owners[@i].IdOwner" />
    <input type="hidden" value="@Model.Owner.IdProcess" name="Owners[@i].IdProcess" />
    <input type="hidden" value="@Model.Owner.IdOwnerType" name="Owners[@i].IdOwnerType" />
    <div class="form-row align-items-end">
        <div class="form-group col-lg-2 col-4">
            <label>Тип</label>
            <input type="text" class="form-control" readonly value="@Model.Owner.IdOwnerTypeNavigation.OwnerType1" />
        </div>
        @if (Model.Owner.IdOwnerType == 1 && Model.Owner.OwnerPerson != null)
        {
            var colName = canEdit ? "col-lg-2 col-4" : "col-lg-3 col-4";
        <input type="hidden" value="@Model.Owner.OwnerPerson.IdOwner" name="Owners[@i].OwnerPerson.IdOwner" />
        <div class="form-group col-lg-3 col-8">
            <label>Фамилия</label>
            <input type="text" class="form-control input-chars rr-owner-surname" placeholder="Фамилия" title="Фамилия"
                   value="@Model.Owner.OwnerPerson.Surname" name="Owners[@i].OwnerPerson.Surname" />
        </div>
        <div class="form-group @colName">
            <label>Имя</label>
            <input type="text" class="form-control input-chars rr-owner-name" placeholder="Имя" title="Имя"
                   value="@Model.Owner.OwnerPerson.Name" name="Owners[@i].OwnerPerson.Name" />
        </div>
        <div class="form-group col-lg-3 col-4">
            <label>Отчество</label>
            <input type="text" class="form-control input-chars" placeholder="Отчество" title="Отчество"
                   value="@Model.Owner.OwnerPerson.Patronymic" name="Owners[@i].OwnerPerson.Patronymic" />
        </div>
        }
        @if (Model.Owner.IdOwnerType != 1 && Model.Owner.OwnerOrginfo != null)
        {
            var colOrgName = canEdit ? "col-lg-8 col-4" : "col-lg-9 col-4";
        <input type="hidden" value="@Model.Owner.OwnerOrginfo.IdOwner" name="Owners[@i].OwnerOrginfo.IdOwner" />
        <div class="form-group @colOrgName">
            <label>Наименование</label>
            <input type="text" class="form-control rr-owner-org-name" placeholder="Наименование"
                   value="@Model.Owner.OwnerOrginfo.OrgName" name="Owners[@i].OwnerOrginfo.OrgName" />
        </div>
        }
        @{
            var colPanel = canEdit ? "btn-group col-lg-2 col-4" : "col-lg-1 col-4 text-right";
        }
        <div class="form-group @colPanel" role="group">
            @if (canEdit)
            {
            <a href="#" class="btn btn-success rr-owner-reason-add" title="Добавить реквизит права собственности">
                <span class="oi oi-plus"></span>
            </a>
            <a href="#" class="btn btn-danger rr-owner-delete" title="Удалить" aria-label="Удалить">
                <span class="oi oi-x"></span>
            </a>
            }
            <a href="#" class="btn btn-primary rr-owner-reasons-toggle" title="Развернуть список документов">
                <span class="oi oi-chevron-top"></span>
            </a>
        </div>
    </div>
</li>
@for (var j = 0; j < Model.Owner.OwnerReasons.Count(); j++)
{
<partial name="OwnerReason" model="@(new OwnerReasonVM() {
    OwnerReason = Model.Owner.OwnerReasons[j],
    I = i,
    J = j,
    Action = ViewBag.Action }) " />
}

RegistryWeb/Views/OwnerProcesses/OwnerFile.cshtml
@using RegistryWeb.Enums;
@model RegistryServices.ViewModel.Owners.OwnerFileVM;
@{
    var i = Model.I;
    var canEdit = Model.Action == ActionTypeEnum.Create || Model.Action == ActionTypeEnum.Edit;
}
<li class="list-group-item">
    <input type="hidden" value="@Model.OwnerFile.Id" name="OwnerFiles[@i].Id" />
    <input type="hidden" value="@Model.OwnerFile.IdProcess" name="OwnerFiles[@i].IdProcess" />
    <div class="form-row align-items-end">
        <div class="form-group col-3">
            <label>Дата загрузки</label>
            <input type="date" class="form-control" value="@(Model.OwnerFile.DateDownload.ToString("yyyy-MM-dd"))"
                   name="OwnerFiles[@i].DateDownload" title="Дата загрузки" readonly>
        </div>
        @{
            var inputFileCol = canEdit ? "col-lg-8 col-7" : "col-lg-9 col-9";
        }
        <div class="form-group @inputFileCol">
            <label>Образ документа</label>
            <div class="input-group">
                <input type="text" maxlength="255" readonly class="form-control rr-file" value="@Model.OwnerFile.FileDisplayName"
                       name="OwnerFiles[@i].FileDisplayName" title="Наименование">
                <input type="file" name="attachmentFiles" style="position: absolute; left: -9999px; width: 1px; height: 1px" />
                <input type="hidden" name="removeFiles" value="false" data-isempty="@(Model.OwnerFile.FileDisplayName == null ? true : false)" />
                <div class="input-group-append">
                    @if (!canEdit)
                    {
                        <a class="btn btn-success rr-owner-file-download @(Model.OwnerFile.FileOriginName == null ? "disabled" : "")"
                           href="/OwnerProcesses/DownloadFile/?id=@Model.OwnerFile.Id" title="Скачать образ документа" aria-label="Скачать образ документа">
                            <span class="oi oi-data-transfer-download"></span>
                        </a>
                    }
                    @if (Model.Action == ActionTypeEnum.Edit)
                    {
                        <a href="#" class="btn btn-danger rr-owner-file-remove"
                           title="Удалить образ документа" aria-label="Удалить образ документа">
                            <span class="oi oi-trash"></span>
                        </a>
                        <a href="#" class="btn btn-success rr-owner-file-attach"
                           title="Прикрепить образ документа" aria-label="Прикрепить образ документа">
                            <span class="oi oi-paperclip"></span>
                        </a>
                        <a class="btn btn-success rr-owner-file-download"
                           href="/OwnerProcesses/DownloadFile/?id=@Model.OwnerFile.Id" title="Скачать образ документа" aria-label="Скачать образ документа">
                            <span class="oi oi-data-transfer-download"></span>
                        </a>
                    }
                    @if (Model.Action == ActionTypeEnum.Create)
                    {
                        <a href="#" class="btn btn-danger rr-owner-file-remove"
                           title="Удалить образ документа" aria-label="Удалить образ документа">
                            <span class="oi oi-x"></span>
                        </a>
                        <a href="#" class="btn btn-success rr-owner-file-attach"
                           title="Прикрепить образ документа" aria-label="Прикрепить образ документа">
                            <span class="oi oi-paperclip"></span>
                        </a>
                    }
                </div>
            </div>
        </div>
        @if (canEdit)
        {
            <div class="form-group col-lg-1 col-2 text-right">
                <a href="#" class="btn btn-danger rr-owner-file-document-delete" title="Удалить" aria-label="Удалить">
                    <span class="oi oi-x"></span>
                </a>
            </div>
        }
    </div>
</li>

RegistryWeb/Views/OwnerProcesses/OwnerProcessAddress.cshtml
@using RegistryWeb.Enums;
@model RegistryServices.ViewModel.Owners.OwnerProcessAddressVM;
@{
    string assocName = "";
    string idName = "";
    if (Model.AddressType == AddressTypes.Building)
    {
        assocName = "OwnerBuildingsAssoc";
        idName = "IdBuilding";
    }
    else if (Model.AddressType == AddressTypes.Premise)
    {
        assocName = "OwnerPremisesAssoc";
        idName = "IdPremise";
    }
    else if (Model.AddressType == AddressTypes.SubPremise)
    {
        assocName = "OwnerSubPremisesAssoc";
        idName = "IdSubPremise";
    }
    var nameAttrIdProcess = assocName + "[" + Model.I + "].IdProcess";
    var nameAttrIdAssoc = assocName + "[" + Model.I + "].IdAssoc";
    var nameAttrId = assocName + "[" + Model.I + "]." + idName;
    var href = Model.Href + $"&returnUrl={Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}";
}
<li class="list-group-item col-12" data-i="@Model.I" data-addresstype="@Model.AddressType">
    <input type="hidden" value="@Model.IdProcess" name="@nameAttrIdProcess" />
    <input type="hidden" value="@Model.IdAssoc" name="@nameAttrIdAssoc" />
    <input type="hidden" value="@Model.Id" name="@nameAttrId" />
    <div class="input-group">
        <input type="text" class="form-control rr-address" disabled title="@Model.Text" value="@Model.Text" />
        <div class="input-group-append d-inline-block">
            <a href="#" class="btn btn-secondary addressInfoToggleBtn">
                <span class="oi oi-info"></span>
            </a>
        </div>
        <div class="input-group-append d-inline-block">
            <a href="@href" class="btn btn-success">
                <span class="oi oi-home"></span>
            </a>
        </div>
        @if (Model.Action == ActionTypeEnum.Create || Model.Action == ActionTypeEnum.Edit)
        {
            <div class="input-group-append h-auto d-inline-block">
                <a href="#" class="btn btn-danger addressDeleteBtn">
                    <span class="oi oi-x"></span>
                </a>
            </div>
        }
    </div>
    <div class="row mt-2 info" style="display: none;">
        <div class="col-4 input-group" title="Комнатность" >
            <div class="input-group-prepend">
                <span class="input-group-text">Ком</span>
            </div>
            <input type="text" readonly class="form-control" />
        </div>
        <div class="col-4 input-group" title="Общая площадь">
            <div class="input-group-prepend">
                <span class="input-group-text">S<sub>общ</sub></span>
            </div>
            <input type="text" readonly class="form-control" />
        </div>
        <div class="col-4 input-group" title="Жилая площадь">
            <div class="input-group-prepend">
                <span class="input-group-text">S<sub>жил</sub></span>
            </div>
            <input type="text" readonly class="form-control" />
        </div>
    </div>
</li>