RegistryWeb/Controllers/KumiPaymentsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RegistryDb.Models.Entities.KumiAccounts;
using RegistryPaymentsLoader;
using RegistryPaymentsLoader.TffFileLoaders;
using RegistryPaymentsLoader.TffStrings;
using RegistryServices.ViewModel.KumiAccounts;
using RegistryWeb.DataServices;
using RegistryWeb.SecurityServices;
using RegistryWeb.ViewOptions.Filter;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RegistryWeb.Extensions;
using RegistryWeb.ViewOptions;
using RegistryWeb.Enums;
using RegistryDb.Models.Entities.Claims;
using RegistryServices.Enums;
using Microsoft.AspNetCore.Authorization;
using RegistryServices.DataServices.KumiPayments;
using RegistryServices.DataServices.KumiAccounts;
using RegistryWeb.DataServices.Claims;
using RegistryWeb.Filters;

namespace RegistryWeb.Controllers
{
    [Authorize]
    [HasPrivileges(Privileges.AccountsRead)]
    [DefaultResponseOnException(typeof(Exception))]
    public class KumiPaymentsController : ListController<KumiPaymentsDataService, KumiPaymentsFilter>
    {
        private readonly KumiAccountsDataService kumiAccountsDataService;
        private readonly KumiPaymentsDistributionsService distributionsService;
        private readonly KumiPaymentsMemorialOrdersService memorialOrdersService;
        private readonly KumiUntiedPaymentsService untiedPaymentsService;
        private readonly ClaimsDataService claimsDataService;
        private readonly TenancyProcessesDataService tenancyProcessesDataService;
        private readonly ZipArchiveDataService zipArchiveDataService;

        public KumiPaymentsController(KumiPaymentsDataService dataService, 
            KumiAccountsDataService kumiAccountsDataService,
            KumiPaymentsDistributionsService distributionsService,
            KumiPaymentsMemorialOrdersService memorialOrdersService,
            KumiUntiedPaymentsService untiedPaymentsService,
            ClaimsDataService claimsDataService,
            TenancyProcessesDataService tenancyProcessesDataService, 
            SecurityService securityService, ZipArchiveDataService zipArchiveDataService)
            : base(dataService, securityService)
        {
            this.kumiAccountsDataService = kumiAccountsDataService;
            this.distributionsService = distributionsService;
            this.memorialOrdersService = memorialOrdersService;
            this.untiedPaymentsService = untiedPaymentsService;
            this.claimsDataService = claimsDataService;
            this.tenancyProcessesDataService = tenancyProcessesDataService;
            this.zipArchiveDataService = zipArchiveDataService;

            nameFilteredIdsDict = "filteredPaymentsIdsDict";
            nameIds = "idPayments";
            nameMultimaster = "PaymentsMassDistributeForm";
        }

        public IActionResult Index(KumiPaymentsVM viewModel, bool isBack = false)
        {
            if (viewModel.PageOptions != null && viewModel.PageOptions.CurrentPage < 1)
                return NotFound();
            if (isBack)
            {
                viewModel.OrderOptions = HttpContext.Session.Get<OrderOptions>("OrderOptions");
                viewModel.PageOptions = HttpContext.Session.Get<PageOptions>("PageOptions");
                viewModel.FilterOptions = HttpContext.Session.Get<KumiPaymentsFilter>("FilterOptions");
            }
            else
            {
                HttpContext.Session.Remove("OrderOptions");
                HttpContext.Session.Remove("PageOptions");
                HttpContext.Session.Remove("FilterOptions");
            }
            ViewBag.SecurityService = securityService;
            ViewBag.KbkDescriptions = dataService.KbkDescriptions;
            ViewBag.PaymentUfSigners = dataService.PaymentUfSigners.Select(r => new { r.IdRecord, Snp = (r.Surname + " " + r.Name + " " + r.Patronymic).Trim() });
            ViewBag.Regions = dataService.Regions;
            ViewBag.Streets = dataService.Streets;
            ViewBag.AccountStates = dataService.AccountStates;
            ViewBag.ClaimStateTypes = dataService.ClaimStateTypes;

            var vm = dataService.GetViewModel(
                viewModel.OrderOptions,
                viewModel.PageOptions,
                viewModel.FilterOptions, out List<int> filteredPaymentsIds);

            ViewBag.UntiedPayments = untiedPaymentsService.GetUntiedPayments(viewModel.FilterOptions?.IdAccount, viewModel.FilterOptions?.IdClaim, viewModel.FilterOptions?.IdCharge);

            AddSearchIdsToSession(vm.FilterOptions, filteredPaymentsIds);

            return View(vm);
        }

        private IActionResult GetView(int? idPayment, string returnUrl, ActionTypeEnum action)
        {
            KumiPayment payment = new KumiPayment {
                IdSource = 1
            };
            if (action != ActionTypeEnum.Create)
            {
                if (!idPayment.HasValue)
                    return NotFound();
                payment = dataService.GetKumiPayment(idPayment.Value);
                if (payment == null)
                    return NotFound();
            }
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.Action = action;
            ViewBag.SecurityService = securityService;
            ViewBag.PaymentGroups = dataService.PaymentGroups;
            ViewBag.PaymentInfoSources = dataService.PaymentInfoSources.Select(r => new { r.IdSource, Name = "("+r.Code+") " + r.Name });
            ViewBag.PaymentDocCodes = dataService.PaymentDocCodes.Select(r => new { r.IdPaymentDocCode, Name = "(" + r.Code + ") " + r.Name });
            ViewBag.PaymentKinds = dataService.PaymentKinds.Select(r => new { r.IdPaymentKind, Name = "(" + r.Code + ") " + r.Name });
            ViewBag.OperationTypes = dataService.OperationTypes.Select(r => new { r.IdOperationType, Name = "(" + r.Code + ") " + r.Name });
            ViewBag.KbkTypes = dataService.KbkTypes.Select(r => new { r.IdKbkType, Name = "(" + r.Code + ") " + r.Name });
            ViewBag.KbkDescriptions = dataService.KbkDescriptions;
            ViewBag.PaymentReasons = dataService.PaymentReasons.Select(r => new { r.IdPaymentReason, Name = "(" + r.Code + ") " + r.Name });
            ViewBag.PayerStatuses = dataService.PayerStatuses.Select(r => new { r.IdPayerStatus, Name = "(" + r.Code + ") " + r.Name });
            ViewBag.PaymentUfSigners = dataService.PaymentUfSigners.Select(r => new { r.IdRecord, Snp = (r.Surname + " " + r.Name + " " + r.Patronymic).Trim() });
            ViewBag.Regions = dataService.Regions;
            ViewBag.Streets = dataService.Streets;
            ViewBag.AccountStates = dataService.AccountStates;
            ViewBag.ClaimStateTypes = dataService.ClaimStateTypes;

            return View("Payment", payment);
        }

        [HttpGet]
        [HasPrivileges(Privileges.AccountsReadWrite)]
        public IActionResult Create(string returnUrl)
        {
            return GetView(null, returnUrl, ActionTypeEnum.Create);
        }

        [HttpGet]
        public IActionResult Details(int? idPayment, string returnUrl)
        {
            return GetView(idPayment, returnUrl, ActionTypeEnum.Details);
        }

        [HttpGet]
        [HasPrivileges(Privileges.AccountsReadWrite)]
        public IActionResult Edit(int? idPayment, string returnUrl)
        {
            return GetView(idPayment, returnUrl, ActionTypeEnum.Edit);
        }

        [HttpGet]
        [HasPrivileges(Privileges.AccountsReadWrite)]
        public IActionResult Delete(int? idPayment, string returnUrl)
        {
            return GetView(idPayment, returnUrl, ActionTypeEnum.Delete);
        }

        [HttpPost]
        [HasPrivileges(Privileges.AccountsReadWrite)]
        public IActionResult Create(KumiPayment kumiPayment)
        {
            var canEdit = kumiPayment.IdSource == 1;
            if (!canEdit)
                return View("NotAccess");
            if (kumiPayment == null)
                return NotFound();
            if (ModelState.IsValid)
            {
                dataService.Create(kumiPayment);
                return RedirectToAction("Details", new { kumiPayment.IdPayment });
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [HasPrivileges(Privileges.AccountsReadWrite)]
        public IActionResult Delete(KumiPayment kumiPayment)
        {
            var dbPayment = dataService.GetKumiPayment(kumiPayment.IdPayment);
            var canEdit = dbPayment.IdSource == 1;
            if (!canEdit)
                return View("NotAccess");
            if (kumiPayment == null)
                return NotFound();

            if (dbPayment.PaymentClaims.Any() || dbPayment.PaymentCharges.Any())
                return Error("Нельзя удалить распределенный платеж");

            dataService.Delete(kumiPayment.IdPayment);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [HasPrivileges(Privileges.AccountsReadWrite)]
        public IActionResult Edit(KumiPayment kumiPayment)
        {
            var dbPayment = dataService.GetKumiPayment(kumiPayment.IdPayment);
            var canEditAll = dbPayment.IdSource == 1;
            if (kumiPayment == null)
                return NotFound();
            if (ModelState.IsValid)
            {
                if (canEditAll && !(dbPayment.PaymentClaims.Any() || dbPayment.PaymentCharges.Any()))
                    dataService.Edit(kumiPayment);
                else
                    dataService.UpdateDescription(dbPayment.IdPayment, kumiPayment.Description);
                return RedirectToAction("Details", new { kumiPayment.IdPayment });
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [HasPrivileges(Privileges.AccountsWrite, Model = -2, ViewResultType = typeof(JsonResult))]
        public IActionResult AddPaymentUf(int? IdPayment)
        {

RegistryWeb/Views/KumiAccounts/Components/ChargeRowComponent/Default.cshtml
@model KumiCharge

<tr class="@(ViewBag.Count - ViewBag.Index + 1 > 12 ? "rr-charge-archive" : "") @(Model.EndDate == ViewBag.ForecastCalcDate ? "rr-charge-current-month-row" : "") @(ViewBag.CurrentPeriodCalced ? "rr-charge-current-month-row-no-calc" : "")" data-charge-end-date="@Model.EndDate.ToString("yyyy-MM-dd")">

    <td class="text-center p-1"><b>@Model.EndDate.ToString("dd.MM.yyyy")</b></td>

    @if (ViewBag.IdAccountCurrent != null)
    {
        if (Model.IdAccount == ViewBag.IdAccountCurrent)
        {
            <td class="text-center p-1" title="Текущий лицевой счет"><b>@Model.Account.Account</b></td>
        }
        else
        {
            <td class="text-center p-1">@Model.Account.Account</td>
        }
    }
    @* Найм *@
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-input-tenancy">@Model.InputTenancy</td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-input-penalty">@Model.InputPenalty</td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-tenancy">@Model.ChargeTenancy</td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-penalty">@Model.ChargePenalty</td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-payment-tenancy">
        @if (ViewBag.HasPayments)
        {
            <a asp-controller="KumiPayments" target="_blank" title="Из них по исковым работам @ViewBag.TenancyOnClaim руб." asp-action="Index"
               asp-route-filterOptions.IdCharge="@Model.IdCharge" )">@Model.PaymentTenancy</a>
        }
        else
        {
            @Model.PaymentTenancy
        }
    </td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-payment-penalty">
        @if (ViewBag.HasPayments)
        {
            <a asp-controller="KumiPayments" target="_blank" title="Из них по исковым работам @ViewBag.PenaltyOnClaim руб." asp-action="Index"
               asp-route-filterOptions.IdCharge="@Model.IdCharge">@Model.PaymentPenalty</a>
        }
        else
        {
            @Model.PaymentPenalty
        }
    </td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-recalc-tenancy">@(Model.RecalcTenancy + Model.CorrectionTenancy)</td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-recalc-penalty">@(Model.RecalcPenalty + Model.CorrectionPenalty)</td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-output-tenancy">@Model.OutputTenancy</td>
    <td class="text-center p-1 rr-charge-tenancy @ViewBag.InitTenancyTabClass rr-charge-period-output-penalty">@Model.OutputPenalty</td>

    @* ДГИ *@
    @if (ViewBag.HasDgiCharges)
    {
        <td class="text-center p-1 rr-charge-dgi d-none rr-charge-period-input-dgi">@Model.InputDgi</td>
        <td class="text-center p-1 rr-charge-dgi d-none rr-charge-period-dgi">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? Model.ChargeDgi : 0)</td>
        <td class="text-center p-1 rr-charge-dgi d-none rr-charge-period-payment-dgi">
            @if (ViewBag.HasPayments)
            {
                <a asp-controller="KumiPayments" target="_blank" title="Из них по исковым работам @ViewBag.DgiOnClaim руб." asp-action="Index"
                   asp-route-filterOptions.IdCharge="@Model.IdCharge" )">@Model.PaymentDgi</a>
            }
            else
            {
                @Model.PaymentDgi
            }
        </td>
        <td class="text-center p-1 rr-charge-dgi d-none rr-charge-period-recalc-dgi">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? Model.RecalcDgi + Model.CorrectionDgi : 0)</td>
        <td class="text-center p-1 rr-charge-dgi d-none rr-charge-period-output-dgi">@Model.OutputDgi</td>
    }
    @* ПКК *@
    @if (ViewBag.HasPkkCharges)
    {
        <td class="text-center p-1 rr-charge-pkk d-none rr-charge-period-input-pkk">@Model.InputPkk</td>
        <td class="text-center p-1 rr-charge-pkk d-none rr-charge-period-pkk">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? Model.ChargePkk : 0)</td>
        <td class="text-center p-1 rr-charge-pkk d-none rr-charge-period-payment-pkk">
            @if (ViewBag.HasPayments)
            {
                <a asp-controller="KumiPayments" target="_blank" title="Из них по исковым работам @ViewBag.PkkOnClaim руб." asp-action="Index"
                   asp-route-filterOptions.IdCharge="@Model.IdCharge" )">@Model.PaymentPkk</a>
            }
            else
            {
                @Model.PaymentPkk
            }
        </td>
        <td class="text-center p-1 rr-charge-pkk d-none rr-charge-period-recalc-pkk">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? Model.RecalcPkk + Model.CorrectionPkk : 0)</td>
        <td class="text-center p-1 rr-charge-pkk d-none rr-charge-period-output-pkk">@Model.OutputPkk</td>
    }
    @* Падун *@
    @if (ViewBag.HasPadunCharges)
    {
        <td class="text-center p-1 rr-charge-padun d-none rr-charge-period-input-padun">@Model.InputPadun</td>
        <td class="text-center p-1 rr-charge-padun d-none rr-charge-period-padun">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? Model.ChargePadun : 0)</td>
        <td class="text-center p-1 rr-charge-padun d-none rr-charge-period-payment-padun">
            @if (ViewBag.HasPayments)
            {
                <a asp-controller="KumiPayments" target="_blank" title="Из них по исковым работам @ViewBag.PadunOnClaim руб." asp-action="Index"
                   asp-route-filterOptions.IdCharge="@Model.IdCharge" )">@Model.PaymentPadun</a>
            }
            else
            {
                @Model.PaymentPadun
            }
        </td>
        <td class="text-center p-1 rr-charge-padun d-none rr-charge-period-recalc-padun">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? Model.RecalcPadun + Model.CorrectionPadun : 0)</td>
        <td class="text-center p-1 rr-charge-padun d-none rr-charge-period-output-padun">@Model.OutputPadun</td>
    }

    @* Всего *@
    @if (ViewBag.HasDgiCharges || ViewBag.HasPkkCharges || ViewBag.HasPadunCharges)
    {
        <td class="text-center p-1 rr-charge-total rr-charge-period-input-all">@(Model.InputTenancy + Model.InputDgi + Model.InputPkk + Model.InputPadun)</td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-input-all-penalty">@Model.InputPenalty</td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-all">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? (Model.ChargeTenancy + Model.ChargeDgi + Model.ChargePkk + Model.ChargePadun) : 0)</td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-all-penalty">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? Model.ChargePenalty : 0)</td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-payment-all">
            @if (ViewBag.HasPayments)
            {
                <a asp-controller="KumiPayments" target="_blank" title="Из них по исковым работам @ViewBag.TotalOnClaim руб." asp-action="Index"
                   asp-route-filterOptions.IdCharge="@Model.IdCharge" )">@(Model.PaymentTenancy + Model.PaymentDgi + Model.PaymentPkk + Model.PaymentPadun)</a>
            }
            else
            {
                @(Model.PaymentTenancy + Model.PaymentDgi + Model.PaymentPkk + Model.PaymentPadun)
            }
        </td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-payment-all-penalty">
            @if (ViewBag.HasPayments)
            {
                <a asp-controller="KumiPayments" target="_blank" title="Из них по исковым работам @ViewBag.PenaltyOnClaim руб." asp-action="Index"
                   asp-route-filterOptions.IdCharge="@Model.IdCharge">@Model.PaymentPenalty</a>
            }
            else
            {
                @Model.PaymentPenalty
            }
        </td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-recalc-all">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? (Model.RecalcTenancy + Model.CorrectionTenancy + Model.RecalcDgi + Model.CorrectionDgi + Model.RecalcPkk + Model.CorrectionPkk + Model.RecalcPadun + Model.CorrectionPadun) : 0)</td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-recalc-all-penalty">@(Model.EndDate != ViewBag.ForecastCalcDate || ViewBag.CurrentPeriodCalced ? Model.RecalcPenalty + Model.CorrectionPenalty : 0)</td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-output-all">@(Model.OutputTenancy + Model.OutputDgi + Model.OutputPkk + Model.OutputPadun)</td>
        <td class="text-center p-1 rr-charge-total rr-charge-period-output-all-penalty">@Model.OutputPenalty</td>
    }
</tr>