RegistryWeb/Controllers/ClaimsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RegistryWeb.Extensions;
using RegistryWeb.SecurityServices;
using RegistryWeb.ViewOptions;
using RegistryWeb.ViewOptions.Filter;
using RegistryServices.ViewModel.Claims;
using RegistryDb.Models.Entities.Claims;
using RegistryServices.Enums;
using RegistryWeb.DataServices.Claims;
using RegistryServices.DataServices.Claims;
using RegistryWeb.Filters;

namespace RegistryWeb.Controllers
{
    [Authorize]
    [HasPrivileges(Privileges.ClaimsRead)]
    [DefaultResponseOnException(typeof(Exception))]
    public class ClaimsController : ListController<ClaimsDataService, ClaimsFilter>
    {
        private readonly ClaimsAssignedAccountsDataService assignedAccountsService;

        public ClaimsController(ClaimsDataService dataService,
            ClaimsAssignedAccountsDataService assignedAccountsService, SecurityService securityService)
            : base(dataService, securityService)
        {
            nameFilteredIdsDict = "filteredClaimsIdsDict";
            nameIds = "idClaims";
            nameMultimaster = "ClaimsReports";
            this.assignedAccountsService = assignedAccountsService;
        }

        public IActionResult Index(ClaimsVM viewModel, bool isBack = false)
        {
            if (viewModel.PageOptions != null && viewModel.PageOptions.CurrentPage < 1)
                return NotFound();
            if (isBack)
            {
                viewModel.OrderOptions = HttpContext.Session.Get<OrderOptions>("OrderOptions");
                viewModel.PageOptions = HttpContext.Session.Get<PageOptions>("PageOptions");
                viewModel.FilterOptions = HttpContext.Session.Get<ClaimsFilter>("FilterOptions");
            }
            else
            {
                HttpContext.Session.Remove("OrderOptions");
                HttpContext.Session.Remove("PageOptions");
                HttpContext.Session.Remove("FilterOptions");
            }
            ViewBag.SecurityService = securityService;
            ViewBag.SignersReports = dataService.Signers.Where(r => r.IdSignerGroup == 2).ToList();

            var vm = dataService.GetViewModel(
                viewModel.OrderOptions,
                viewModel.PageOptions,
                viewModel.FilterOptions, out List<int> filteredTenancyProcessesIds);

            AddSearchIdsToSession(vm.FilterOptions, filteredTenancyProcessesIds);

            return View(vm);
        }

        public IActionResult Details(int? idClaim, string returnUrl)
        {
            if (idClaim == null)
                return NotFound();
            var claim = dataService.GetClaim(idClaim.Value);
            if (claim == null)
                return NotFound();
            InitializeViewBag("Details", returnUrl, securityService.HasPrivilege(Privileges.ClaimsWrite));
            var claimVM = dataService.GetClaimViewModel(claim);
            return View("Claim", claimVM);
        }

        [HasPrivileges(Privileges.ClaimsWrite)]
        public ActionResult Create(int? idAccountBks, int? idAccountKumi)
        {
            InitializeViewBag("Create", null, true);
            return View("Claim", dataService.CreateClaimEmptyViewModel(idAccountBks, idAccountKumi));
        }

        [HttpPost]
        [HasPrivileges(Privileges.ClaimsWrite)]
        public ActionResult Create(ClaimVM claimVM)
        {
            if (claimVM == null || claimVM.Claim == null)
                return NotFound();
            if (ModelState.IsValid)
            {
                dataService.Create( claimVM.Claim,
                    HttpContext.Request.Form.Files.Select(f => f).ToList(), claimVM.LoadPersonsSource);
                return RedirectToAction("Details", new { claimVM.Claim.IdClaim });
            }
            InitializeViewBag("Create", null, true);
            return View("Claim", dataService.GetClaimViewModel(claimVM.Claim));
        }

        public ActionResult GetClaimPersonsBySource(LoadPersonsSourceEnum loadPersonsSource, int? idAccountBks, int? idAccountKumi)
        {
            var persons = new List<ClaimPerson>();
            switch (loadPersonsSource)
            {
                case LoadPersonsSourceEnum.Tenancy:
                    persons = dataService.GetClaimPersonsFromTenancy(idAccountBks, idAccountKumi);
                    break;
                case LoadPersonsSourceEnum.PrevClaim:
                    persons = dataService.GetClaimPersonsFromPrevClaim(idAccountBks, idAccountKumi);
                    break;
            }
            return PartialView("ClaimPersonsPreview", persons);
        }

        [HasPrivileges(Privileges.ClaimsWrite)]
        public ActionResult Edit(int? idClaim, string returnUrl)
        {
            if (idClaim == null)
                return NotFound();

            var claim = dataService.GetClaim(idClaim.Value);
            if (claim == null)
                return NotFound();

            InitializeViewBag("Edit", returnUrl, true);
            return View("Claim", dataService.GetClaimViewModel(claim));
        }

        [HttpPost]
        [HasPrivileges(Privileges.ClaimsWrite)]
        public ActionResult Edit(ClaimVM claimVM, string returnUrl)
        {
            if (claimVM == null || claimVM.Claim == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                dataService.Edit(claimVM.Claim);
                return RedirectToAction("Details", new { claimVM.Claim.IdClaim });
            }
            InitializeViewBag("Edit", returnUrl, true);
            return View("Claim", dataService.GetClaimViewModel(claimVM.Claim));
        }

        [HasPrivileges(Privileges.ClaimsWrite)]
        public ActionResult Delete(int? idClaim, string returnUrl)
        {
            if (idClaim == null)
                return NotFound();

            var claim = dataService.GetClaim(idClaim.Value);
            if (claim == null)
                return NotFound();

            InitializeViewBag("Delete", returnUrl, false);
            return View("Claim", dataService.GetClaimViewModel(claim));
        }

        [HttpPost]
        [HasPrivileges(Privileges.ClaimsWrite)]
        public ActionResult Delete(ClaimVM claimVM)
        {
            if (claimVM == null || claimVM.Claim == null)
                return NotFound();

            dataService.Delete(claimVM.Claim.IdClaim);
            return RedirectToAction("Index");
        }

        private void InitializeViewBag(string action, string returnUrl, bool canEditBaseInfo)
        {
            ViewBag.Action = action;
            ViewBag.CanEditBaseInfo = canEditBaseInfo;
            if (returnUrl != null)
            {
                ViewBag.ReturnUrl = returnUrl;
            }
            ViewBag.SecurityService = securityService;
            ViewBag.SignersReports = dataService.Signers.Where(r => r.IdSignerGroup == 2).ToList();
        }

        [HttpPost]
        public JsonResult GetAccounts(string text, string type, bool excludeAnnual)
        {
            var accounts = assignedAccountsService.GetAccounts(text, type, excludeAnnual);
            return Json(accounts.Select(pa => new {
                pa.IdAccount,
                pa.Account
            }));
        }

        [HttpPost]
        public JsonResult GetAccountInfo(int idAccount, string type)
        {
            if (type == "BKS")
            {
                var account = assignedAccountsService.GetAccountBks(idAccount);
                var rentObjects = assignedAccountsService.GetRentObjectsBks(new List<int> { idAccount });
                var lastPaymentInfo = assignedAccountsService.GetLastPaymentsInfo(new List<int> { idAccount }).Select(v => v.Value).FirstOrDefault();
                return Json(new
                {
                    PaymentAccount = account?.Account,
                    BksAddress = account?.RawAddress,
                    RegistryAddress = rentObjects.ContainsKey(idAccount) ? rentObjects[idAccount].Select(r => r.Text).Aggregate((acc, v) => acc + ", " + v) : "",
                    AmountTenancy = lastPaymentInfo?.BalanceOutputTenancy,
                    AmountPenalties = lastPaymentInfo?.BalanceOutputPenalties,
                    AmountDgi = lastPaymentInfo?.BalanceOutputDgi,
                    AmountPadun = lastPaymentInfo?.BalanceOutputPadun,
                    AmountPkk = lastPaymentInfo?.BalanceOutputPkk
                });
            } else
            if (type == "KUMI")
            {
                var account = assignedAccountsService.GetAccountKumi(idAccount);
                var address = assignedAccountsService.GetAccountAddress(idAccount);
                
                return Json(new
                {
                    RegistryAddress = address,
                    AmountTenancy = account.CurrentBalanceTenancy,
                    AmountPenalties = account.CurrentBalancePenalty,
                    AmountDgi = account.CurrentBalanceDgi,
                    AmountPkk = account.CurrentBalancePkk,
                    AmountPadun = account.CurrentBalancePadun
                });
            }
            return Json(null);
        }

        [HttpPost]
        [HasPrivileges(Privileges.ClaimsWrite, Model = -2, ViewResultType = typeof(JsonResult))]
        public IActionResult AddClaimState(string action, int idClaim)
        {
            var claim= dataService.GetClaim(idClaim) ?? new Claim { ClaimStates = new List<ClaimState>(), ClaimCourtOrders = new List<ClaimCourtOrder>() };
            var claimStates = claim.ClaimStates;
            ViewBag.SecurityService = securityService;
            ViewBag.Action = action;
            ViewBag.StateTypes = dataService.StateTypes;
            ViewBag.StateTypeRelations = dataService.StateTypeRelations;
            claimStates.Add(new ClaimState {

RegistryWeb/Controllers/PrivRealtorsController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RegistryWeb.DataServices;
using RegistryDb.Models;
using RegistryWeb.SecurityServices;
using RegistryWeb.ViewOptions;
using RegistryDb.Models.Entities.Privatization;
using RegistryWeb.Filters;
using System;

namespace RegistryWeb.Controllers
{
    [Authorize]
    [DefaultResponseOnException(typeof(Exception))]
    public class PrivRealtorsController : RegistryBaseController
    {
        private readonly RegistryContext rc;
        private readonly SecurityService securityService;
        private readonly PrivRealtorService dataService;

        public PrivRealtorsController(RegistryContext rc, SecurityService securityService, PrivRealtorService dataService)
        {
            this.rc = rc;
            this.securityService = securityService;
            this.dataService = dataService;
        }

        public IActionResult Index(PageOptions pageOptions)
        {
            return View(dataService.GetViewModel(pageOptions));
        }

        public IActionResult Create()
        {
            ViewBag.Action = "Create";
            return View("PrivRealtor", dataService.GetPrivRealtorView(new PrivRealtor()));
        }

        [HttpPost]
        public IActionResult Create(PrivRealtor privRealtor)
        {
            if (privRealtor == null)
                return NotFound();
            if (ModelState.IsValid)
            {
                dataService.Create(privRealtor);
                return RedirectToAction("Index");
            }
            return View("PrivRealtor", dataService.GetPrivRealtorView(privRealtor));
        }

        public IActionResult Edit(int? idRealtor)
        {
            ViewBag.Action = "Edit";
            if (idRealtor == null)
                return NotFound();
            var privRealtor = rc.PrivRealtors.FirstOrDefault(ort => ort.IdRealtor == idRealtor);
            if (privRealtor == null)
                return NotFound();
            return View("PrivRealtor", dataService.GetPrivRealtorView(privRealtor));
        }

        [HttpPost]
        public IActionResult Edit(PrivRealtor privRealtor)
        {
            if (privRealtor == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                dataService.Edit(privRealtor);
                return RedirectToAction("Index");
            }

            return View("PrivRealtor", dataService.GetPrivRealtorView(privRealtor));
        }

        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? idRealtor)
        {
            ViewBag.Action = "Delete";
            if (idRealtor == null)
                return NotFound();
            var privRealtor = rc.PrivRealtors.FirstOrDefault(ort => ort.IdRealtor == idRealtor);
            if (privRealtor == null)
                return NotFound();
            return View("PrivRealtor", dataService.GetPrivRealtorView(privRealtor));
        }

        [HttpPost]
        public IActionResult Delete(PrivRealtor privRealtor)
        {
            if (privRealtor == null)
                return NotFound();

            var privRealtorOld = rc.PrivRealtors.FirstOrDefault(ort => ort.IdRealtor == privRealtor.IdRealtor);
            if (privRealtorOld != null)
            {
                dataService.Delete(privRealtorOld);
                return RedirectToAction("Index");
            }
            return Error("Не удалось удалить риелтора. Обратитесь к администратору");            
        }
    }
}

RegistryWeb/Controllers/ReformaGKHController.cs
using RegistryWeb.SecurityServices;
using RegistryWeb.DataServices;
using RegistryReformaGKH;
using Microsoft.AspNetCore.Authorization;

namespace RegistryWeb.Controllers
{
    [Authorize]
    public class ReformaGKHController : RegistryBaseController
    {
        private readonly ReformaGKHService reformaGKH;
        private readonly SecurityService securityService;
        private readonly TokenApiStorage storage;

        public ReformaGKHController(ReformaGKHService reformaGKH, SecurityService securityService, TokenApiStorage storage)
        {
            this.reformaGKH = reformaGKH;
            this.securityService = securityService;
            this.storage = storage;
        }

        //public IActionResult Index()
        //{
        //    if (!securityService.HasPrivilege(Privileges.OwnerReadWrite))
        //        return View("NotAccess");
        //    ViewData["SessionGuid"] = storage.SessionGuid;
        //    return View();
        //}

        //public IActionResult Test()
        //{
        //    try
        //    {
        //        var entity1 = ApiTest.GetHouseProfileActualResult();
        //        var xDoc = reformaGKH.Serialize<HouseProfileActualResult>(entity1);
        //        xDoc.Save(@"D:\houseProfileActualResult.xml");
        //        var entity2 = reformaGKH.Deserialize<HouseProfileActualResult>(xDoc);
        //    }
        //    catch (Exception ex)
        //    {
        //        return Content("Ошибка! \n" + ex.Message);
        //    }
        //    ViewData["SessionGuid"] = storage.SessionGuid;
        //    return View("Index");
        //}

        //public IActionResult Login(LoginVM model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            var xDoc = reformaGKH.Login(model.User, model.Password);
        //        }
        //        catch (Exception ex)
        //        {
        //            return Content("Ошибка! \n" + ex.Message);
        //        }
        //    }
        //    ViewData["SessionGuid"] = storage.SessionGuid;
        //    return View("Index",model);
        //}

        //public IActionResult GetReportingPeriodList()
        //{
        //    try
        //    {
        //        var xDoc = reformaGKH.GetReportingPeriodList();
        //        var list = xDoc.Descendants("GetReportingPeriodListResult").SingleOrDefault();
        //        xDoc = new XDocument(new XElement("PeriodListResult", list));
        //        var pr = reformaGKH.Deserialize<PeriodListResult>(xDoc);
        //    }
        //    catch (Exception ex)
        //    {
        //        return Content("Ошибка! \n" + ex.Message);
        //    }
        //    ViewData["SessionGuid"] = storage.SessionGuid;
        //    return View("Index");
        //}

        //public IActionResult GetHouseProfileActual()
        //{
        //    try
        //    {
        //        var xDoc = reformaGKH.GetHouseProfileActual(8939273);
        //        var list = xDoc.Descendants("GetHouseProfileActualResult").SingleOrDefault();
        //        xDoc = new XDocument(new XElement("HouseProfileActualResult",
        //            new XAttribute(XNamespace.Xmlns + "xsi", list.GetNamespaceOfPrefix("xsi")),
        //            list.Elements()));
        //        var entity = reformaGKH.Deserialize<HouseProfileActualResult>(xDoc);
        //    }
        //    catch (Exception ex)
        //    {
        //        return Content("Ошибка! \n" + ex.Message);
        //    }
        //    ViewData["SessionGuid"] = storage.SessionGuid;
        //    return View("Index");
        //}
    }
}

RegistryWeb/Views/Shared/NotAccess.cshtml
@{ 
    ViewData["Title"] = "Нет доступа";
}
<h1 class="text-danger text-center">Недостаточно прав!</h1>

RegistryWeb/Views/Shared/UnsupportedBrowser.cshtml
@{
    ViewData["Title"] = "Браузер не поддерживается";
    <div class="container mt-4 text-center">
        <h2 class="text-danger">Ваш браузер не поддерживается!</h2>
        <h5 class="offset-md-1 col-md-10 text-danger text-break">Воспользуйтесь одним из следующих браузеров или позвоните диспетчеру МКУ «ЦИТиТО» 349-671</h5>
        <div class="row">
            <div class="col-4 offset-md-1 col-md-2 mt-5 text-center">
                <img src="~/image/browsers/chrome.png" style="width: 80%" alt="Google Chrome">
                <h5 class="mt-2">Google Chrome</h5>
            </div>
            <div class="col-4 col-md-2 mt-5 text-center">
                <img src="~/image/browsers/firefox.png" style="width: 80%" alt="Mozilla Firefox">
                <h5 class="mt-2">Mozilla Firefox</h5>
            </div>
            <div class="col-4 col-md-2 mt-5 text-center">
                <img src="~/image/browsers/edge.png" style="width: 80%" alt="Microsoft Edge">
                <h5 class="mt-2">Microsoft Edge</h5>
            </div>
            <div class="offset-2 col-4 offset-md-0 col-md-2 mt-5 text-center">
                <img src="~/image/browsers/opera.png" style="width: 80%" alt="Opera">
                <h5 class="mt-2">Opera</h5>
            </div>
            <div class="col-4 col-md-2 mt-5 text-center">
                <img src="~/image/browsers/yandex.png" style="width: 80%" alt="Yandex Browser">
                <h5 class="mt-2">Yandex Browser</h5>
            </div>
        </div>
    </div>
  
}

RegistryWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ЖФ</title>
    <link rel="shortcut icon" href="~/home.png" type="image/x-icon">
    <link href="~/lib/bootstrap-4.3.1/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/open-iconic-master/font/css/open-iconic-bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker3.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-select-1.13.9/dist/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap4-toggle/css/bootstrap4-toggle.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/autocomplete.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)

    <script type="text/javascript">
        if ((window.navigator.userAgent.indexOf("MSIE ") > 0 || window.navigator.userAgent.indexOf("Trident") > 0) &&
            location.pathname != "/Home/UnsupportedBrowser") {
            location.href = "/Home/UnsupportedBrowser"
        }
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap-4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-input-spinner/src/bootstrap-input-spinner.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/lib/bootstrap-datepicker/locales/bootstrap-datepicker.ru.min.js"></script>
    <script src="~/lib/bootstrap-select-1.13.9/dist/js/bootstrap-select.min.js"></script>
    <script src="~/lib/bootstrap4-toggle/js/bootstrap4-toggle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/Inputmask-5.x/dist/jquery.inputmask.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">

            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/home.png" width="30" height="30" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-lg-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownObjects" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Жилые объекты</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownObjects">
                            <a class="dropdown-item" asp-area="" asp-controller="Buildings" asp-action="Index">Здания</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Premises" asp-action="Index">Помещения</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#" id="areaAvgCostModalBtn">Цена вторичного жилья</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="RegistryObjectsReports" asp-action="Index">Отчеты</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownOwners" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Собственность</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownOwners">
                            <a class="dropdown-item" asp-area="" asp-controller="OwnerProcesses" asp-action="Index">Процессы собственности</a>
                            <a class="dropdown-item" asp-area="" asp-controller="OwnerReasonTypes" asp-action="Index">Типы оснований</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="OwnerReports" asp-action="Index">Отчеты</a>
                            @*<a class="dropdown-item" asp-area="" asp-controller="ReformaGKH" asp-action="Index">Реформа ЖКХ</a>*@
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownTenancies" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Найм жилья</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownTenancies">
                            <a class="dropdown-item" asp-area="" asp-controller="TenancyProcesses" asp-action="Index">Процессы найма</a>
                            <a class="dropdown-item" asp-area="" asp-controller="DocumentIssued" asp-action="Index">Паспортные столы</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="TenancyObjectsReports" asp-action="Index">Отчеты</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownClaims" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ПИР и ЛС (найм)</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownClaims">
                            <a class="dropdown-item" asp-area="" asp-controller="KumiPayments" asp-action="Index">Платежи</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="PaymentAccounts" asp-action="Index">Лицевые счета БКС</a>
                            <a class="dropdown-item" asp-area="" asp-controller="KumiAccounts" asp-action="Index">Лицевые счета КУМИ</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="Claims" asp-action="Index">Претензионно-исковые работы</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="ClaimReports" asp-action="Index">Отчеты</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownObjects" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Мена жилья</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownObjects">
                            <a class="dropdown-item" href="http://mena/">Договоры мены</a>
                            <a class="dropdown-item" href="http://mena/DocumentIssued/">Паспортные столы</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPrivatization" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Приватизация</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownPrivatization">
                            <a class="dropdown-item" asp-area="" asp-controller="Privatization" asp-action="Index">Договоры приватизации</a>
                            <a class="dropdown-item" asp-area="" asp-controller="PrivRealtors" asp-action="Index">Риелторы</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="PrivatizationReports" asp-action="Index">Отчеты</a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="ml-auto align-middle d-none d-xl-block">
                @await Component.InvokeAsync("DatabaseNameComponent")
            </div>
            <div class="ml-auto align-middle d-none d-xl-block">
                <a asp-controller="PersonalSetting" asp-action="Details" class="btn btn-link">@User.Identity.Name</a>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>